# Generated by Django 5.1.7 on 2025-04-04 21:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('search_manager', '0001_initial'),
    ]

    operations = [
    ]
