# Generated by Django 5.1.7 on 2025-04-04 16:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MissingPerson',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=255)),
                ('age', models.PositiveIntegerField()),
                ('gender', models.CharField(blank=True, choices=[('M', 'Male'), ('F', 'Female'), ('O', 'Other')], max_length=1, null=True)),
                ('last_seen_date', models.DateTimeField()),
                ('last_seen_location', models.CharField(max_length=255)),
                ('contact_phone', models.CharField(max_length=20)),
                ('additional_info', models.TextField(blank=True)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='missing_persons/')),
                ('status', models.CharField(choices=[('missing', 'Missing'), ('found', 'Found'), ('resolved', 'Case Resolved')], default='missing', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('reported_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reported_persons', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Missing Person',
                'verbose_name_plural': 'Missing Persons',
                'ordering': ['-created_at'],
            },
        ),
    ]
