# Generated by Django 5.1.7 on 2025-05-11 19:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core_app', '0002_livevideosource_missingpersonimage_recordedvideo'),
    ]

    operations = [
        migrations.CreateModel(
            name='SearchMatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('confidence_score', models.FloatField(blank=True, null=True)),
                ('snapshot_image', models.ImageField(blank=True, help_text='A snapshot frame where the match occurred.', null=True, upload_to='search_snapshots/%Y/%m/%d/')),
                ('live_video_source', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='matches_found_via_source', to='core_app.livevideosource')),
                ('missing_person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='search_matches', to='core_app.missingperson')),
            ],
            options={
                'verbose_name': 'Search Match',
                'verbose_name_plural': 'Search Matches',
                'ordering': ['-timestamp'],
            },
        ),
    ]
